### ISSUE TITLE
Crash with earlier Ryu versions and routing enabled.

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#336]
Since commit 8c62149ae57ad13fd0f35a3562e8df892e392338 we have introduced a regression with Faucet routing and versions of Ryu <v4.9 which don't support the **enable_ipv6** argument.

Stack trace is here:

> ubuntu@faucet:~$ sudo start-faucet  
> loading app /usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet//faucet.py
> Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
> Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
> loading app ryu.controller.ofp_handler
> instantiating app None of DPSet
> creating context dpset
> instantiating app /usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet//faucet.py of Faucet
> API method core.start called with args: {'router_id': '127.0.0.2', 'label_range': (100, 100000), 'waiter': <ryu.lib.hub.Event object at 0x7f9c90a56d90>, 'local_as': 9727, 'bgp_server_port': 9179, 'refresh_max_eor_time': 0, 'refresh_stalepath_time': 0}
> API method network.add called with args: {'prefix': '202.74.195.254/22', 'next_hop': '202.74.195.254'}
> API method network.add called with args: {'prefix': '172.16.0.3/24', 'next_hop': '172.16.0.3'}
> API method network.add called with args: {'prefix': '2401:7000:69:4000::ffff/64', 'next_hop': '2401:7000:69:4000::ffff'}
> API method network.add called with args: {'prefix': '2401:7000:69:43e8::f/124', 'next_hop': '2401:7000:69:43e8::f'}
> API method network.add called with args: {'prefix': 'fe80::20d:88ff:fe00:aa/64', 'next_hop': 'fe80::20d:88ff:fe00:aa'}
> API method network.add called with args: {'prefix': '2401:7000:69:4000::fffe/128', 'next_hop': '2401:7000:69:4000::fffe'}
> API method network.add called with args: {'prefix': '2401:7000:69::/64', 'next_hop': '2401:7000:69:43e8::3'}
> Traceback (most recent call last):
>   File "/usr/local/bin/ryu-manager", line 11, in <module>
>     load_entry_point('ryu==4.8.1', 'console_scripts', 'ryu-manager')()
>   File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 91, in main
>     services.extend(app_mgr.instantiate_apps(**contexts))
>   File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
>     self._instantiate(app_name, cls, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 495, in _instantiate
>     app = cls(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/faucet.py", line 121, in __init__
>     self._reset_bgp()
>   File "/usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/faucet.py", line 201, in _reset_bgp
>     bgp_speakers[vlan] = self._create_bgp_speaker_for_vlan(vlan)
>   File "/usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/faucet.py", line 186, in _create_bgp_speaker_for_vlan
>     enable_ipv6=True)
> TypeError: neighbor_add() got an unexpected keyword argument 'enable_ipv6'

**Comment by gizmoguy** [comment]
We will fix by depending on ryu v4.9 from now on.

**Comment by gizmoguy** [comment]
I have done this in PR #339. I think I got all the references?
