### ISSUE TITLE
Crash when using comments in faucet.yaml

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#358]
At the moment we tend to crash when using entire-line comments in faucet.yaml.

Say for example you want to document an ACL rule:

>         # Allow unicast ipv6 from fe80::/64
>         - rule:
>             dl_type: 0x86dd
>             nw_src: fe80::/64
>             actions:
>                 allow: 1

Pyyaml will parse and remove everything after (and including) the # which means the config parse will get fed a blank line with spaces on it.

This tends to give us the following crash:

> Traceback (most recent call last):
>   File "/usr/local/bin/ryu-manager", line 9, in <module>
>     load_entry_point('ryu==4.9', 'console_scripts', 'ryu-manager')()
>   File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 81, in main
>     services.extend(app_mgr.instantiate_apps(**contexts))
>   File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
>     self._instantiate(app_name, cls, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 495, in _instantiate
>     app = cls(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/faucet.py", line 105, in __init__
>     self.config_file, self.logname)
> TypeError: 'NoneType' object is not iterable

**Comment by gizmoguy** [comment]
Work around is to remove all the spaces before a comment so that pyyaml evaluates to an empty line which faucet ignores.

**Comment by gizmoguy** [comment]
Ok I'm really not sure what caused this issue now, I have managed to get comments working fine with indentation so it must have been something else.

Closing for now.
