### ISSUE TITLE
Python 3.x porting issues

### ISSUE THREAD

**Issue by byllyfish** [REANNZ/faucet#473]
I'm running faucet (latest master) under python 3.6.  I encountered two issues related to the Python 3.x port that are easy to fix.

Issue 1 occurs at start up. 

```
Traceback (most recent call last):
  File "/home/mininet/venv36/bin/ryu-manager", line 11, in <module>
    load_entry_point('ryu==4.12', 'console_scripts', 'ryu-manager')()
  File "/home/mininet/venv36/lib/python3.6/site-packages/ryu/cmd/manager.py", line 81, in main
    services.extend(app_mgr.instantiate_apps(**contexts))
  File "/home/mininet/venv36/lib/python3.6/site-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
    self._instantiate(app_name, cls, *args, **kwargs)
  File "/home/mininet/venv36/lib/python3.6/site-packages/ryu/base/app_manager.py", line 495, in _instantiate
    app = cls(*args, **kwargs)
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 189, in __init__
    self.config_file, self.logname)
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/config_parser.py", line 35, in dp_parser
    config_hashes, dps = _config_parser_v2(config_file, logname)
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/config_parser.py", line 148, in _config_parser_v2
    top_confs['vlans'])
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/config_parser.py", line 85, in _dp_parser_v2
    dp.sanity_check()
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/dp.py", line 141, in sanity_check
    assert isinstance(self.dp_id, (int, long))
NameError: name 'long' is not defined
```

Issue 2 occurs with ICMPv6 neighbor discovery resolving.  I configured an IPv6 faucet_vip and then  ping'd it from host fc00::1.  A while later, it will log a traceback to the console when the ND request is sent to check if fc00::1 is still there.

```
Mar 20 13:52:00 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:00 faucet.valve INFO     Responded to ND solicit for fc00::10:10:10:1 to fc00::1 (92:06:7e:ac:62:d6)
Mar 20 13:52:00 faucet.valve INFO     learned 2 hosts on vlan 2040
Mar 20 13:52:00 faucet.valve INFO     Adding new route fc00::1/128 via fc00::1 (92:06:7e:ac:62:d6)
Mar 20 13:52:00 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:01 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:02 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:02 faucet.valve INFO     learned 2 hosts on vlan 2040
Mar 20 13:52:03 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:04 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:04 faucet.valve INFO     learned 2 hosts on vlan 2040
Mar 20 13:52:05 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:06 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:92:06:7e:ac:62:d6 in_port:1 vid:2040
Mar 20 13:52:06 faucet.valve INFO     learned 2 hosts on vlan 2040
Mar 20 13:53:06 faucet.valve INFO     expiring host f2:5f:74:ae:72:0b from vlan 2040
Mar 20 13:53:06 faucet.valve INFO     1 recently active hosts on vlan 2040
Mar 20 13:55:44 faucet.valve DEBUG    Packet_in DPID 1 (0x1) src:f2:5f:74:ae:72:0b in_port:2 vid:2040
Mar 20 13:55:44 faucet.valve INFO     learned 2 hosts on vlan 2040
Mar 20 13:57:10 faucet.valve INFO     expiring host 92:06:7e:ac:62:d6 from vlan 2040
Mar 20 13:57:10 faucet.valve INFO     1 recently active hosts on vlan 2040
Mar 20 14:00:26 faucet.valve INFO     resolving fc00::1
Mar 20 14:00:29 faucet.valve INFO     resolving fc00::1 retry 2 (last attempt was 3s ago)
Mar 20 14:00:36 faucet.valve INFO     resolving fc00::1 retry 3 (last attempt was 7s ago)
```

Note: there is no additional logging in the faucet_exception.log or faucet.log, and the process does NOT terminate.

```
Faucet: Exception occurred during handler processing. Backtrace from offending handler [resolve_gateways] servicing event [EventFaucetResolveGateways] follows.
Traceback (most recent call last):
  File "/home/mininet/venv36/lib/python3.6/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 385, in resolve_gateways
    flowmods = valve.resolve_gateways()
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 1112, in resolve_gateways
    ofmsgs.extend(self.ipv6_route_manager.resolve_gateways(vlan, now))
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_route.py", line 342, in resolve_gateways
    ip_gw, faucet_vip, vlan, ports))
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_route.py", line 109, in _neighbor_resolver
    vid, faucet_vip, ip_gw)
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_route.py", line 602, in _neighbor_resolver_pkt
    self.faucet_mac, vid, faucet_vip.ip, ip_gw)
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_packet.py", line 182, in nd_request
    nd_mac = ipv6_link_eth_mcast(dst_ip)
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_packet.py", line 151, in ipv6_link_eth_mcast
    mcast_mac = ':'.join(['%02X' % ord(x) for x in mcast_mac_bytes])
  File "/home/mininet/code/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_packet.py", line 151, in <listcomp>
    mcast_mac = ':'.join(['%02X' % ord(x) for x in mcast_mac_bytes])
TypeError: ord() expected string of length 1, but int found
```

I replaced the offending code with a call to:

```python
def _bytes_to_mac(value):
    if isinstance(value, str):
        return ':'.join(['%02X' % ord(x) for x in value])
    return ':'.join(['%02X' % x for x in value])
```

**Comment by byllyfish** [comment]
I removed `ipaddr` from requirements.txt; the version of ipaddr on pypi is not python3 compatible (even though the latest github version is). 

You've switched over to the `ipaddress` module.

```console
$ pip install -r requirements.txt
Collecting ipaddr (from -r requirements.txt (line 6))
  Downloading ipaddr-2.1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lbmh7z6a/ipaddr/setup.py", line 19, in <module>
        import ipaddr
      File "/tmp/pip-build-lbmh7z6a/ipaddr/ipaddr.py", line 1450
        ip_int = 0L
                  ^
    SyntaxError: invalid syntax
```

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/502/commits

Fixes the long type problem, I'll work on the unicode handling next (the problem goes beyond this).

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/503/commits

Fixes the byte/unicode problem referenced in this bug.

NOTE: of course, we're still not quite ready to run under python3, but this fixes the problems referenced in this bug.

Thanks for reporting the problems.
