### ISSUE TITLE
Group support for routing is flakey

### ISSUE THREAD

**Issue by anarkiwi** [REANNZ/faucet#593]
Often fails under TravisCI.

======================================================================
ERROR: test_untagged (__main__.FaucetSingleGroupTableUntaggedIPv4RouteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 293, in tearDown
    self.verify_no_exception('FAUCET_EXCEPTION_LOG')
  File "/faucet-src/tests/faucet_mininet_test_base.py", line 278, in verify_no_exception
    msg='%s log contains %s' % (exception_log, exception_contents))
AssertionError: FAUCET_EXCEPTION_LOG log contains May 14 02:44:02 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/faucet-src/faucet/valve_util.py", line 52, in __koe
    func(*args, **kwargs)
  File "/faucet-src/faucet/faucet.py", line 528, in _packet_in_handler
    dp_id, self.valves, in_port, vlan_vid, pkt)
  File "/faucet-src/faucet/valve.py", line 1061, in rcv_packet
    ofmsgs.extend(self._learn_host(valves, dp_id, pkt_meta))
  File "/faucet-src/faucet/valve.py", line 899, in _learn_host
    route_manager.add_host_fib_route_from_pkt(pkt_meta))
  File "/faucet-src/faucet/valve_route.py", line 446, in add_host_fib_route_from_pkt
    self._add_host_fib_route(pkt_meta.vlan, src_ip))
  File "/faucet-src/faucet/valve_route.py", line 393, in _add_host_fib_route
    return self.add_route(vlan, host_ip, host_route)
  File "/faucet-src/faucet/valve_route.py", line 380, in add_route
    is_updated=False))
  File "/faucet-src/faucet/valve_route.py", line 154, in _add_resolved_route
    group_id=self.ip_gw_to_group_id[ip_gw])])]
KeyError: IPv4Address(u'10.0.0.2')

**Comment by anarkiwi** [comment]
Fixed by https://github.com/REANNZ/faucet/commit/cdc66105008d1bf3a5fc4a9051e2a4ea864e90ac
