### ISSUE TITLE
Gauge crashes when unknown DP connects

### ISSUE THREAD

**Issue by anarkiwi** [REANNZ/faucet#689]
Jun 06 18:55:49 gauge.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/faucet/valve_util.py", line 54, in __koe
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/faucet/gauge.py", line 137, in handler_reconnect
    for watcher in list(self.watchers[ryu_dp.id].values()):
KeyError: 15400387541834

**Comment by anarkiwi** [comment]
self.config_file = os.getenv('GAUGE_CONFIG', self.config_file)

        new_confs = watcher_parser(self.config_file, self.logname)
        new_watchers = {}
        for conf in new_confs:
            watcher = watcher_factory(conf)(conf, self.logname)
            new_watchers.setdefault(watcher.dp.dp_id, {})
            new_watchers[watcher.dp.dp_id][watcher.conf.type] = watcher
