### ISSUE TITLE
Long datapath IDs break faucet due to metric code

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#698]
```
Jun 08 14:13:35 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/faucet/valve_util.py", line 54, in __koe
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/faucet/faucet.py", line 305, in _packet_in_handler
    valve.update_metrics(self.metrics)
  File "/usr/local/lib/python2.7/dist-packages/faucet/valve.py", line 1041, in update_metrics
    if int(label_dict['dpid'], 16) == self.dp.dp_id:
ValueError: invalid literal for int() with base 16: '0xe6a9e89a8fbe0c32L'
```

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/699
