### ISSUE TITLE
Other exceptions Gauge needs to handle from InfluxDB

### ISSUE THREAD

**Issue by anarkiwi** [REANNZ/faucet#771]
Jul 07 06:47:49 gauge.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 360, in recv_into
    return self._recv_loop(self.fd.recv_into, 0, buffer, nbytes, flags)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 348, in _recv_loop
    self._read_trampoline()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 319, in _read_trampoline
    timeout_exc=socket.timeout("timed out"))
  File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='172.17.0.1', port=8086): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 54, in __koe
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/faucet/gauge.py", line 209, in port_stats_reply_handler
    ryu_event.msg.datapath.id, 'port_stats', ryu_event.msg)
  File "/usr/local/lib/python3.5/dist-packages/faucet/gauge.py", line 185, in _update_watcher
    self.watchers[dp_id][name].update(rcv_time, dp_id, msg)
  File "/usr/local/lib/python3.5/dist-packages/faucet/watcher.py", line 405, in update
    if not self.ship_points(points):
  File "/usr/local/lib/python3.5/dist-packages/faucet/watcher.py", line 71, in ship_points
    return client.write_points(points=points, time_precision='s')
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 456, in write_points
    tags=tags, protocol=protocol)
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 506, in _write_points
    protocol=protocol
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 302, in write
    headers=headers
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 247, in request
    timeout=self._timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='172.17.0.1', port=8086): Read timed out. (read timeout=10)

**Comment by anarkiwi** [comment]
https://github.com/REANNZ/faucet/pull/786
